### ISSUE TITLE
[ENHANCEMENT] Improve format Github action

### ISSUE THREAD

**Issue by mtfishman** [ITensor/ITensors.jl#803]
We could try this Github action for formatting:
```yml
name: Format suggestions

on:
  pull_request:

concurrency:
  # Skip intermediate builds: always.
  # Cancel intermediate builds: only if it is a pull request build.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@latest
        with:
          version: 1
      - run: |
          julia  -e 'using Pkg; Pkg.add("JuliaFormatter")'
          julia  -e 'using JuliaFormatter; format("."; verbose=true)'
      - uses: reviewdog/action-suggester@v1
        with:
          tool_name: JuliaFormatter
          fail_on_error: true
          filter_mode: added
```
used by [ChainRulesCore.jl](https://github.com/JuliaDiff/ChainRulesCore.jl/blob/95612d0860f9356a426e3372aafce7feb4e933d0/.github/workflows/format.yml), which I think actually makes suggestions for formatting issues to change on the PR (whereas ours currently just says if there is a formatting issue, but doesn't suggest a change to make).
